#!/usr/bin/env python
#

import sys

from config0_publisher.loggerly import Config0Logger
from config0_publisher.resource.manage import ResourceCmdHelper

class Main(ResourceCmdHelper):

    def __init__(self,**kwargs):

        ResourceCmdHelper.__init__(self,
                                   app_name="ansible",
                                   set_must_exists=["stateful_id"])

        self.classname = 'ANSIBLE_PRIVATE_KEY'

        self.logger = Config0Logger(self.classname,
                                    logcategory="cloudprovider")

        self.logger.debug("Instantiating %s" % self.classname)
        self.set_inputargs(add_app_vars=True)

        # if you want to remap vars for the application in the inputargs
        # e.g. ANS_VAR_mongodb_public_ips to mongodb_public_ips
        self.remap_app_vars()

    def create(self):

        filepath = "{}/ssh_key.pem".format(self.exec_dir)

        self.write_key_to_file(key="private_key",
                               filepath=filepath,
                               split_char="return",
                               deserialize=True,
                               add_return=True,
                               permission=400)

        self.logger.debug("#"*32)
        self.logger.debug("ssh key file written to {}".format(filepath))
        self.logger.debug("#"*32)

def usage():

    print("""
script + environmental variables

or

script + json_input (as argument)

environmental variables:

    create:
        JOB_INSTANCE_ID
        SCHEDULE_ID
        RUN_ID
        METHOD
        ANS_VAR_private_key

       """)
    exit(4)

if __name__ == '__main__':

    try:
        json_input = sys.argv[1]
    except:
        json_input = None

    main = Main()

    if main.inputargs.get("method","create") == "create":

        main.check_required_inputargs(keys=["private_key"])
        main.create()

    else:
        usage()
        print('method "{}" not supported!'.format(main.inputargs.get("method","create")))
        exit(4)
